# Generated by Django 6.0.2 on 2026-02-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('part-time', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('apply_link', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
