# Generated by Django 6.0.2 on 2026-02-07 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('data', 'Data Science'), ('marketing', 'Marketing'), ('writing', 'Writing'), ('management', 'Management'), ('other', 'Other')], default='other', max_length=50)),
                ('embedding', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief professional summary')),
                ('resume_text', models.TextField(blank=True, help_text='Parsed resume content')),
                ('preferred_job_types', models.JSONField(blank=True, default=list, help_text='List of preferred job types: job, internship, freelance, etc.')),
                ('preferred_locations', models.JSONField(blank=True, default=list, help_text="List of preferred locations or 'Remote'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2)),
                ('years_experience', models.FloatField(default=0, help_text='Years of experience with this skill')),
            ],
            options={
                'ordering': ['-proficiency', 'skill__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-scraped_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='Remote', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(help_text='Where this job was scraped from', max_length=100),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('preparing', 'Preparing Application'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='saved', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this opportunity')),
                ('email_draft', models.TextField(blank=True, help_text='AI-generated email draft')),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_explanation', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.job')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='core_job_job_typ_5d260f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='core_job_source_85478d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scraped_at'], name='core_job_scraped_320cdb_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='core.skill'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user_profile', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user_profile', 'skill')},
        ),
    ]
