# Generated by Django 6.0.2 on 2026-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_userprofile_userskill_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_skills',
            field=models.JSONField(blank=True, default=list, help_text='AI-extracted skills list'),
        ),
        migrations.AddField(
            model_name='job',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated job summary'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('any', 'Any Level')], default='', help_text='AI-extracted experience level', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='is_enriched',
            field=models.BooleanField(default=False, help_text='Whether AI enrichment has been applied'),
        ),
        migrations.AddField(
            model_name='job',
            name='role_type',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Full Stack'), ('data', 'Data Science'), ('devops', 'DevOps'), ('design', 'Design'), ('marketing', 'Marketing'), ('management', 'Management'), ('other', 'Other')], default='', help_text='AI-extracted role type', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_enriched'], name='core_job_is_enri_f2b933_idx'),
        ),
    ]
