# Generated by Django 6.0.2 on 2026-04-09 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by', to='core.job'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('source', 'apply_link')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='core_job_is_acti_fa47ed_idx'),
        ),
    ]
