# Generated by Django 6.0.2 on 2026-04-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_swipeevent_userprofile_liked_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='swipeevent',
            new_name='core_swipee_user_pr_ef96e8_idx',
            old_name='core_swipee_user_pr_idx',
        ),
        migrations.RenameIndex(
            model_name='swipeevent',
            new_name='core_swipee_timesta_fbb239_idx',
            old_name='core_swipee_timesta_idx',
        ),
    ]
